export const Images = {
    ACCEPTED_CHECK_MARK: '/images/accepted-check-mark.svg',
    DONE_CHECK_MARK: '/images/done-check-mark.svg',
    EXTERNAL_LINK_BUTTON: '/images/external-link-button.svg',
    LANDING_LOGO: '/images/landing-logo.svg',
    LEFT_ARROW: '/images/left-arrow.svg',
    LESSON: '/images/lesson.svg',
    LESSON_JAVA: '/images/lesson-java.svg',
    LOGO: '/images/logo.svg',
    NECESSITY: '/images/necessity.svg',
    NO_STREAK_FIRE: '/images/no-streak-fire.svg',
    REJECTED_CHECK_MARK: '/images/rejected-check-mark.svg',
    RESET: '/images/reset.svg',
    RESIZE: '/images/resize.svg',
    RIGHT_ARROW: '/images/right-arrow.svg',
    SEARCH: '/images/search.svg',
    STREAK_FIRE: '/images/streak-fire.svg',
    CONSOLE: '/images/console.svg',
    UNSOLVED_CHECK_MARK: '/images/unsolved-checkmark.svg',
    UP_ARROW: '/images/up-arrow.svg',
    GEAR: '/images/gear.svg',
    GOOGLE_ICON: '/images/google-icon.svg',
    FACEBOOK_ICON: '/images/facebook-icon.svg',
    GITHUB_ICON: '/images/github-icon.svg',
    DOWN_FILLED_ARROW: '/images/down-filled-arrow.svg',
    LANDING_CURVE: '/images/landing-curve.svg',
}
