export const Strings = {
    SITE_TITLE: 'Algocourse',
    SITE_DESCRIPTION: 'The most definitive Algorithm and Data Structures course for your coding interview',
    YOUR_STREAK: 'Your Streak',
    DAYS: 'days',
    STREAK_NOTE_DONE: "You're done for the day!",
    STREAK_NOTE_TODO: 'Learn 1 new problem or solve 1 unsolved problem to keep your streak going',
    HOME_PAGE: 'Home Page',
    HOME: 'Home',
    FEATURES: 'Features',
    PRICING: 'Pricing',
    FAQs: 'FAQs',
    CONTACT_US: 'Contact us',
    DASHBOARD: 'Dashboard',
    PROBLEM: 'Problem',
    PRACTICE: 'Practice',
    LEADERBOARD: 'Leaderboard',
    COURSE_CONTENT: 'Course Content',
    LEARN: 'Learn',
    SEE_MORE: 'See more',
    SEE_LESS: 'See less',
    ID: 'ID',
    DIFFICULTY: 'Difficulty',
    COMPANIES: 'Companies',
    ACCEPTED: 'Accepted',
    STATUS: 'Status',
    YOUR_PREGRESS: 'Your Progress',
    LESSONS_LEARNED: 'Lessons learned',
    PROBLEMS_SOLVED: 'Problems solved',
    RANDOM_TIP: 'Random Tip',
    LOGIN: 'Login',
    LOGIN_WITH_FACEBOOK: 'Login with Facebook',
    LOGIN_WITH_GITHUB: 'Login with Github',
    LOGIN_WITH_GOOGLE: 'Login with Google',
    LOGIN_WITH_YOUR_SOCIAL_ACCOUNTS: 'Login with your social accounts',
    COURSE_NOTICE: "We recommend you to learn from left to right, top to bottom for the best experience and result.",
    BACK_TO_ALL_TOPICS: 'Back to all topics',
    LESSONS: 'LESSONS',
    BACK: 'Back',
    NEXT: 'Next',
    SOLUTION: 'Solution',
    SUBMISSIONS: 'Submissions',
    CUSTOM_INPUT: 'Custom input',
    OUTPUT: 'Output',
    PREV: 'Prev',
    DASHBOARD_SEARCH_PLACEHOLDER: 'Search for lessons and problems'
}
