apiVersion: v1
kind: Pod
metadata:
  name: nextjs
spec:
  containers:
  - image: algocourse/frontend-development:latest
    name: nextjs
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
      protocol: TCP