export const Strings = {
    SITE_TITLE: 'Algocourse',
    SITE_DESCRIPTION: 'The most definitive Algorithm and Data Structures course for your coding interview',
    YOUR_STREAK: 'Your Streak',
    DAYS: 'days',
    STREAK_NOTE_DONE: "You're done for the day!",
    STREAK_NOTE_TODO: 'Learn 1 new problem or solve 1 unsolved problem to keep your streak going',
    HOME_PAGE: 'Home Page',
    HOME: 'Home',
    FEATURES: 'Features',
    PRICING: 'Pricing',
    FAQs: 'FAQs',
    CONTACT_US: 'Contact us',
    DASHBOARD: 'Dashboard',
    PROBLEMS: 'Problems',
    PROBLEM: 'Problem',
    PRACTICE: 'Practice',
    LEADERBOARD: 'Leaderboard',
    COURSE_CONTENT: 'Course Content',
    LEARN: 'Learn',
    SEE_MORE: 'See more',
    SEE_LESS: 'See less',
    ID: 'ID',
    DIFFICULTY: 'Difficulty',
    COMPANIES: 'Companies',
    ACCEPTED: 'Accepted',
    STATUS: 'Status',
    YOUR_PREGRESS: 'Your Progress',
    LESSONS_LEARNED: 'Lessons learned',
    PRACTICE_PROBLEMS_SOLVED: 'Practice problems solved',
}
