export const Strings = {
    SITE_TITLE: 'Algocourse',
    SITE_DESCRIPTION: 'The most definitive Algorithm and Data Structures course for your coding interview',
    YOUR_STREAK: 'Your Streak',
    DAYS: 'days',
    STREAK_NOTE_DONE: "You're done for the day!",
    STREAK_NOTE_TODO: 'Learn 1 new problem or solve 1 unsolved problem to keep your streak going',
    HOME_PAGE: 'Home Page',
    HOME: 'Home',
    FEATURES: 'Features',
    PRICING: 'Pricing',
    FAQs: 'FAQs',
    CONTACT_US: 'Contact us',
    DASHBOARD: 'Dashboard',
    PROBLEMS: 'Problems',
    PRACTICE: 'Practice',
    LEADERBOARD: 'Leaderboard',
}
